### ISSUE TITLE
How to set a <slot>?

### ISSUE THREAD

**Issue by Shackless** [DesignByOnyx/stencil-storybook-starter#5]
Given the following render function of my component: 

```
render() {
    return (
     <button>
       <slot />
     </button>
    );
  }
```

How can I set the `<slot>` content using the configuration in `*.story.ts`?

**Comment by DesignByOnyx** [comment]
This is similar to #1 - and I have an idea to easily provide this functionality. This feature will be in my next update, which should be coming soon.

**Comment by Shackless** [comment]
You're right, sorry. Feel free to close this as a duplicate. I'm eagerly awaiting your solution :)

**Comment by DesignByOnyx** [comment]
Closing as duplicate
